### ISSUE TITLE
Problem adding scriptlink with external script

### ISSUE THREAD

**Issue by ytterstrom** [tavikukko/Chrome-SP-Editor#14] opened 2017-04-28 08:15 UTC
I am trying to add a scriptlink with an external script for example https://code.jquery.com/jquery-3.2.1.min.js but the site refuses to load. SharePoint 2013.

**Comment by koltyakov** [comment] 2017-04-28 08:40
Hi @ytterstrom,

This a SharePoint by design limitation.
ScriptLink user custom actions can't use external scripts.
In the case of necessity appending CDN/external stuff, it should be a local js which appends external scripts into the DOM.

**Comment by tavikukko** [comment] 2017-04-28 09:57
@ytterstrom thanks for reporting this. @koltyakov is correct, its a limitation in SharePoint, but actually in o365 you can inject files from CDN, so this will happen in on-premise version of SharePoint. @ytterstrom did your page/site/web get broken and was it possible to recover using SP Editor by removing the scriptlink?

**Comment by ytterstrom** [comment] 2017-04-28 12:06
The text "external css and js files must use absolute url." under scriptlinks give you the impression that you could link external scripts. I tried linking a script from another SharePoint sitecollection, but that did not work either. This is working when I add the custom action with the pnp provisioning engine, here is a example (the link is in another site collection): 
<pnp:CustomAction Name="{fd098456-b36d-4805-a5d0-12f8c1e1a903}" Description="AddJQuery" Location="ScriptLink" Sequence="0" Rights="" ScriptBlock="&#xD;&#xA;				var headID = document.getElementsByTagName('head')[0]; &#xD;&#xA;				var&#xD;&#xA;				newScript = document.createElement('script');&#xD;&#xA;				newScript.type = 'text/javascript';&#xD;&#xA;				newScript.src = 'https://spapp.dom.se/samarbeteit/Scripts/jquery-1.9.1.min.js';&#xD;&#xA;				headID.appendChild(newScript);" RegistrationType="None">

**Comment by tavikukko** [comment] 2017-04-28 12:17
@ytterstrom thanks! so, would you recommend that it would be clever to check if we are in on-premise, and then inject the file using javascript IF its external file? The problem with those files is that its pretty hard to know when the file is actually loaded when using this technique. I faced this issue and i removed this possibility from the tool cos it was causing loading issues.

**Comment by tavikukko** [comment] 2017-04-28 12:17
but yes, the text "external css and js files must use absolute url." is miss leading, will correct that for the next release.

**Comment by ytterstrom** [comment] 2017-04-28 12:30
I tried to looked at the implementation of UserCustomActions.add in pnp.core.js. In my opinion it would work if I could specify the Payload.Scriptblock. I am not quite following you when you say "it is pretty hard to know when the file is actually loaded". Do you mean regarding to the script sequence? Because even though I have jQuery in the style library with an earlier sequence than the script that uses the library, I always check the jQuery has been loaded before using any functions. And it would be no different if the script has been loaded from an external source. Or have I missunderstood you?

**Comment by tavikukko** [comment] 2017-04-28 12:39
ok, if you add file which resides in sharepoint libaray with sequence 1100, and then you link another file using that **pnp style** with sequence 1000. When you load the page, you can check from chrome dev tool **network** tab, that the page will load the file from sharepoint earlier than the external file, no matter the sequence. This is my only consern.

**Comment by ytterstrom** [comment] 2017-04-28 13:04
Yeah, I agree that I could be a problem. But as I mentioned earlier, I think it is a good practice to check that libraries/functions has been loaded before you call them.

**Comment by ytterstrom** [comment] 2017-04-28 13:13
FYI I used the excellent PnP Js console and embedded the script the following way:
import pnp from "pnp";
pnp.setup({
    headers: {
        "Accept": "application/json;odata=verbose",
    }
});
var payload = {};
  payload.Location = 'ScriptLink';
  payload.Sequence = "0";
  payload.ScriptBlock = "var headID = document.getElementsByTagName('head')[0];	var	newScript = document.createElement('script'); newScript.type = 'text/javascript'; newScript.src = 'https://code.jquery.com/jquery-3.2.1.min.js'; headID.appendChild(newScript);"

pnp.sp.site.userCustomActions.add(payload).then(result => {
	
	console.log(result);
});

**Comment by tavikukko** [comment] 2017-05-24 07:39
@ytterstrom & @koltyakov , I added support for external JS files for on-premises. Its done by using ScriptBlock. Published v2.1.2 version now available in chrome webstore. Will close this now. Thanks for reporting and working with this one. Let me know If you encounter any other issues.

**Closed by tavikukko** 2017-05-24 07:39 UTC

**Comment by koltyakov** [comment] 2017-05-24 08:36
Thanks @tavikukko
