### ISSUE TITLE
blank SharePoint TAB in the devtools(F12)

### ISSUE THREAD

**Issue by eugenjeno** [tavikukko/Chrome-SP-Editor#33] opened 2018-02-05 08:42 UTC
* installed chrome extension(not manually)
* opened sharepoint site and devtools
* selected sharepoint tab, BUT is completely blank

**Comment by tavikukko** [comment] 2018-02-05 10:11
thanks @eugenjeno for reporting! 
Could you specify OS and chrome version you are using, maybe even screenshot, thanks.

**Comment by tavikukko** [comment] 2018-02-28 08:40
@eugenjeno whats the status of this, are you still facing this issue?

**Comment by renefluhler** [comment] 2018-03-02 11:42
Have the same problem
Windows 10 Version 1703, Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Same on PC and Laptop

**Comment by renefluhler** [comment] 2018-03-02 11:44
Disabled all extensions except SP Editor and no change

**Comment by tavikukko** [comment] 2018-03-02 11:52
thanks @renefluhler for reporting.
Could you do following
1. detach the devtools from the browser
2. press ctrl+alt+i to open devtools of sp editor
3. check console for errors

thanks

**Comment by renefluhler** [comment] 2018-03-02 16:23
thanks @tavikukko for the quick reply

I got it to work by opening the browser with the farm admin account
My account is not working even thought I am a farm administrator and site collection admin

No need to look to investigate further
Cheers René

**Comment by tavikukko** [comment] 2018-03-07 15:23
@renefluhler could you help me little with this, other users are also facing similar issues but I cannot reproduce this.
So could you tell me the steps how this situation occurs. 
some questions:
- sharepoint env, online/sp2013/sp2016, language
- account used (member, owner, site collection admin..)

Thanks!!

**Comment by ytterstrom** [comment] 2018-10-26 13:19
If I try to use speditor on a computer where I am not admin, I get a blank screen and the following message:
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

Is there a workaround?

**Comment by tavikukko** [comment] 2018-10-26 14:07
Could you try this https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by ytterstrom** [comment] 2018-10-26 14:10
That is the problem, and a group policy is permitting me from changing this...

**Comment by tavikukko** [comment] 2020-06-19 18:13
closing, please open if still a problem

**Closed by tavikukko** 2020-06-19 18:13 UTC
