### ISSUE TITLE
Path arg to fetch() contains extra "/Web"...

### ISSUE THREAD

**Issue by pkreipke** [tavikukko/Chrome-SP-Editor#32] opened 2017-12-23 00:00 UTC
Going into 'File Editor' on root site. Clicking on any folder like "_catalogs" results in a 404 in the JS console for this fetch():

https://hostname/Web/_api/web/getFolderByServerRelativeUrl('/_catalogs')?$expand=Folders,%20Files

If I try the API call without "/Web" (which matches my code's API calls) then the fetch succeeds.

Same thing happens if I'm in a subsite.

P

**Comment by tavikukko** [comment] 2017-12-23 15:58
Thanks @pkreipke  for reporting.
Which environment you are (online/sp2013/so2016)? Could you provide exact error message you are getting in console, that would help also to find the bug.
Thanks.

**Comment by pkreipke** [comment] 2017-12-23 16:04
On-premise SP 2013. Attached console log of success, then three message from failure which I think are driven by the 404.

[AQC-1514044800631.log](https://github.com/tavikukko/Chrome-SP-Editor/files/1584246/AQC-1514044800631.log)

**Comment by tavikukko** [comment] 2017-12-23 16:30
Just tested File Editor and PnP JS Console on SP2013 root site collection (http://intranet.sp.test/), the executed rest query http://intranet.sp.test/_api/web/getFolderByServerRelativeUrl('/_catalogs')?$expand=Folders,%20Files --> works ok.

**Comment by tavikukko** [comment] 2017-12-23 16:59
@pkreipke also from sub web it works http://intranet.sp.test/mysubweb/_api/web/getFolderByServerRelativeUrl('/mysubweb/_catalogs')?$expand=Folders,%20Files --> works ok. I don't think this is something to do with SP Editor, might be your environment?

**Comment by tavikukko** [comment] 2017-12-23 17:01
oh, I think your rest call is build wrong, https://hostname/Web/_api/web/getFolderByServerRelativeUrl('/_catalogs')?$expand=Folders,%20Files should be https://hostname/Web/_api/web/getFolderByServerRelativeUrl('/Web/_catalogs')?$expand=Folders,%20Files

**Comment by pkreipke** [comment] 2017-12-23 23:11
Yep, that's the issue. Note that in the console log I posted I included at the top a GET that worked correctly. Note that it does NOT contain the preceding "/Web" in the path that is causing the issue in the second fetch().

I'm simply launching your extension from the home page of the site collection and trying to open a file in the extension. E.g. I haven't done anything explicit to cause two different URLs to be used.

Ideas?

**Comment by tavikukko** [comment] 2017-12-24 08:13
Still can't reproduce the issue. If you got more information, that would help. Anything special in the setup, SP patch level, language and so on.

**Comment by tavikukko** [comment] 2018-02-28 08:41
@pkreipke are you still facing this issue?

**Comment by tavikukko** [comment] 2018-10-28 20:10
will close this cos have not heard anything.

**Closed by tavikukko** 2018-10-28 20:10 UTC
