### ISSUE TITLE
Cannot delete a List field by using the delete() function

### ISSUE THREAD

**Issue by navarrorc** [tavikukko/Chrome-SP-Editor#72] opened 2020-04-17 06:34 UTC
I can't delete a field from a List using the delete() function, in the console I get 
```TypeError: list.fields.getByTitle(...).delete is not a function```

To reproduce:

Try to delete a field by following the instructions found at https://pnp.github.io/pnpjs/sp/fields/#delete-a-field

![pnpjs_console_cannot_delete_field](https://user-images.githubusercontent.com/215220/79539130-96855380-803a-11ea-8df3-f23bbb9872e4.png)

**Comment by tavikukko** [comment] 2020-04-17 08:29
Hi @navarrorc 
and thanks for reporting. Could might be a bug actually in PnPjs?

**Comment by tavikukko** [comment] 2020-04-17 10:25
[issue to PnPjs](https://github.com/pnp/pnpjs/issues/1164)

**Comment by navarrorc** [comment] 2020-04-17 16:34
@tavikukko Thank you for creating an issue on the PnPjs repo. I will the code that you provided when reporting the issue.

```javascript
import { SPHttpClient } from "@pnp/sp";

(async () => {

  const client = new SPHttpClient()
  await client.delete(`https://tenant.sharepoint.com/sites/sitecollection/_api/web/lists/getbytitle('testlist')/fields/getbytitle('testcolumn')`)

})().catch(console.log)
```

**Comment by tavikukko** [comment] 2020-04-20 11:17
Closing as the issue is in PnPjs. Thanks!

**Closed by tavikukko** 2020-04-20 11:17 UTC
