### ISSUE TITLE
Issue with Chrome 73 Update

### ISSUE THREAD

**Issue by ckreling** [tavikukko/Chrome-SP-Editor#50] opened 2019-04-05 20:38 UTC
Hi there 

I really love this tool.  With the recent Chrome v 73 update something has broken where I can edit files in File Editor but if I refresh the page and make another change I get the spinning save wheel and have to close the developer tools and start over.  This is repeatable on both Win 7 and Mac.

Thank you for any help !!!!!

**Comment by ckreling** [comment] 2019-04-06 02:33
Hi - update for you

I found v 56 of Chrome and tried again and it appears something in SP has changed to cause some incompatibility with the editor.

To reproduce on PC or Mac 
I am using SP Online

-Open a page with a javascript file to edit embedded
-You can make changes and ctl S and saving works great
-Refresh browser page
-Attempt to save again and spinning arrows save icon - it hangs forever.

Thinking the idea the other person suggested in a recent issue as to allow a 5 second time out and then cancel attempt to save with a prompt would really help here as well.

Thanks !

**Comment by Gennady-G** [comment] 2019-04-06 13:22
Don't know if is related, but tried to rename webpart (change webpart title) in "Page Editor", and  spinning arrows hanged too..

>>omething has broken where I can edit files in File Editor
Try to map file and edit in external editor? Mapping with "Overrides" works Ok.

**Comment by ckreling** [comment] 2019-04-06 15:56
Can you explain mapping with overrides and procedure you use for mapping file to use external EDITOR?  At work I have visual studio to try but also looking for a Mac solution tonite from home.  Thanks for any help.

**Comment by tavikukko** [comment] 2019-04-07 10:07
thanks @ckreling & @Gennady-G for reporting, I will have a look.

**Comment by tavikukko** [comment] 2019-04-07 12:41
@Gennady-G I found a bug in the code of Page Editor, which is now fixed. @ckreling are you talking about File Editor or did you also use Page Editor, because I was not able to reproduce the error in File Editor.

**Comment by tavikukko** [comment] 2019-04-07 13:35
Released new version of SP Editor with the fix to Page Editor. If this fixed also issue with @ckreling, then I will close the bug.
Thanks for your co-operation, really appreciated!

**Comment by ckreling** [comment] 2019-04-08 01:03
HI there @tavikukko - appreciate the quick response.  I had the issue with file editor.  I'll try tomorrow AM and let you know if it still happens.

There was another post where a user asked if you would consider putting a save timeout/cancel feature for when the arrows go into infinite spinning and lock up the tool.  Would you consider making such an enhancement?

Thanks !

**Comment by Gennady-G** [comment] 2019-04-08 05:42
> I found a bug in the code of Page Editor, which is now fixed.
Thank You @tavikukko ! :+1: )

>Can you explain mapping with overrides and procedure you use for mapping file to use external EDITOR?

@ckreling, F12-> Sources -> Overrides, add folder, "Accept", then in "Network" right click, "save for overrides". See [ this thread](https://github.com/tavikukko/Chrome-SP-Editor/issues/30#issuecomment-356041049) or in google (You don't need Canary, Chrome works too). Not than every time You "Edit page" You need to re-add *.css files, they get different tag..

**Comment by tavikukko** [comment] 2019-04-08 09:58
@ckreling cannot reproduce in File Editor, so if you have exact steps how to repro this, it would help to debug.
The timeout is good idea, I will think about it again, but let's get this fixed first. When there is something wrong, and the spinner stays spinning, I think its also good to restart it because there might be something wrong and the next updates could break something...So I think I could add timeout, but instead of just hiding the spinner, I should show a message that "something went wrong, please restart SP Editor to recover and please report in the GitHub issues list"..

**Comment by ckreling** [comment] 2019-04-08 16:35
Hello

Well I just uninstalled and re-installed the editor and have the same issue (but thank you for putting horizontal scroll bar on files list!!!)

Here are the steps to reproduce:

1) Open a SP Online page that has a content editor web part that links to a JavaScript file.
2) F12 and go to SharePoint tab
3) Select File editor
4) Place cursor anywhere on code and 'Ctl-S' to save.  It can be just one time or up to any number of times and it will save all changes.
5) Press F5 to reload page.
6) Click back in code in File editor and try to save with Ctl-S - never ending spinning arrows.

Also noticing that sometimes when I click file editor or page editor nothing comes up and I have to keep clicking back on the links before I see the web parts or the files listings.

Let me know if that helps.

**Comment by tavikukko** [comment] 2019-04-08 17:00
Thank you,
couple of questions:
- between steps 3-4, I search that linked js file and edit that? 
- is that linked js file in the same sitecollection / web as the contenteditor webpart?

The File Editor always works in the same context as the user is, so if you are working on a subsite, the file editor will start browsing down from that particular web, not from the rootweb of the sitecollection.

**Comment by ckreling** [comment] 2019-04-08 19:04
Bullet 1) Not sure what you are asking here?
Bullet 2) Yes it is - same site.  Page with CEWP in SitePages and js in SiteAssets

**Comment by tavikukko** [comment] 2019-04-12 14:47
Can't repro this, sorry. Can you record a short video :) ?

**Comment by tavikukko** [comment] 2020-05-10 20:05
closing, please reopen if the problem still exist

**Closed by tavikukko** 2020-05-10 20:05 UTC
Labels: can't reproduce
