### ISSUE TITLE
File Editor does not catch chrome shortcuts

### ISSUE THREAD

**Issue by johannes-z** [tavikukko/Chrome-SP-Editor#47] opened 2018-11-26 09:27 UTC
For example, I cannot enter a `'` anymore, since this is the hotkey to open the chrome settings on my system:

![image](https://user-images.githubusercontent.com/9069888/49004967-d9a10700-f165-11e8-8ce7-b4b52c91db7d.png)

**Comment by tavikukko** [comment] 2018-11-28 16:52
wow, thanks @johannes-z ! tried with macOS and got the same, but the shortcut is different (cmd+,) Let's see if there is something to make this work. I tested something but could not fix it yet, it might be little hard to override DevTools shortcuts, but let's see.

**Comment by tavikukko** [comment] 2018-11-30 20:40
@johannes-z is this your custom shortcut cos I'm not seeing it in the menu of the Chrome? 
<img width="258" alt="screenshot 2018-11-30 at 22 38 39" src="https://user-images.githubusercontent.com/2223355/49313701-d2288780-f4f0-11e8-8409-a13b9908be7a.png">

**Comment by johannes-z** [comment] 2018-12-01 08:40
It's not in this menu. It's a shortcut of the devtools, not of chrome itself

**Comment by tavikukko** [comment] 2018-12-11 19:03
@johannes-z whats the keyboard language layout and what the key combination to do ' sign? cant reproduce this with Finnish/English keyboards on windows.

**Comment by johannes-z** [comment] 2018-12-12 15:47
@tavikukko I'm on a german (austria) keyboard layout (qwertz). I press these buttons: <kbd>SHIFT</kbd>+<kbd>#</kbd>

**Comment by tavikukko** [comment] 2019-03-08 09:39
@johannes-z could you go to this page https://keycode.info/ and press shift+# and show me the out come with your keyboard settings?
Working on a fix for this now, sorry for the delay.
thanks!

**Comment by johannes-z** [comment] 2019-03-08 12:53
@tavikukko Sure! It's `191`

**Comment by tavikukko** [comment] 2019-03-08 22:02
fixed in latest release 4.5.0

**Closed by tavikukko** 2019-03-08 22:02 UTC
